export const TRIGGER_LOGGEDIN = 'TRIGGER_LOGGEDIN';
export const TRIGGER_FAILURE = 'TRIGGER_FAILURE';
export const TRIGGER_LOADING = 'TRIGGER_LOADING';

// article action types
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_FAILURE = 'FETCH_CATEGORY_FAILURE';
export const FETCH_POPULAR_SUCCESS = 'FETCH_POPULAR_SUCCESS';
export const FETCH_POPULAR_FAILURE = 'FETCH_POPULAR_FAILURE';
// article actions
export const RECEIVE_ARTICLE_SUCCESS = 'RECEIVE_ARTICLE_SUCCESS';

export const FETCH_CATEGORY_TITLES_SUCCESS = 'FETCH_CATEGORY_TITLES_SUCCESS';
export const FETCH_CATEGORY_TITLES_FAILURE = 'FETCH_CATEGORY_TITLES_FAILURE';

export const FETCH_TAG_TITLES_SUCCESS = 'FETCH_TAG_TITLES_SUCCESS';
export const FETCH_TAG_TITLES_FAILURE = 'FETCH_TAG_TITLES_FAILURE';

export const FETCH_AUTHORS_SUCCESS = 'FETCH_AUTHORS_SUCCESS';
export const FETCH_AUTHORS_FAILURE = 'FETCH_AUTHORS_FAILURE';

export const POST_ARTICLE_SUCCESS = 'POST_ARTICLE_SUCCESS';
export const POST_ARTICLE_FAILURE = 'POST_ARTICLE_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const SEARCH_RESULTS_SUCCESS = 'SEARCH_RESULTS_SUCCESS';
export const SEARCH_RESULTS_FAILURE = 'SEARCH_RESULTS_FAILURE';
