export default {
  status: 'success',
  totalPages: 2,
  currentPage: 1,
  totalArticles: 19,
  articlesOnPage: 10,
  articles: [
    {
      id: 19,
      title: 'The 5 Basic Statistics Concepts Data Scientists Need to Know',
      slug: 'how-to-write-you-name-230111fe',
      description: 'If you want to learn a better and more memorable way',
      body: "let's talk about names, what is your name and what does it mean? How many people have laughed at your name and how many have cared about how you name was given to you?",
      readTime: 2400,
      articleImage: 'https://bit.ly/2UysylQ',
      category: 'naming',
      rating: null,
      likes: 0,
      dislikes: 0,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-01-28T11:17:55.507Z',
      updatedAt: '2018-01-28T11:17:55.557Z',
      author: {
        id: 6,
        fullName: 'Terso Artsen',
        avatarUrl: 'https://www.hahafakeurl.com/',
        roleId: 3,
        email: 'solomon.sulaiman@andela.com',
        bio: 'I am a girl that does magic tricks',
        followers: 0,
        following: 0
      }
    },
    {
      id: 18,
      title: 'Why Do Some Men Hurt Women? Because They Like To',
      slug: 'how-to-write-you-name-230111fe',
      description: 'If you want to learn a better and more memorable way',
      body: "let's talk about names, what is your name and what does it mean? How many people have laughed at your name and how many have cared about how you name was given to you?",
      readTime: 2400,
      articleImage: 'https://bit.ly/2rtyQ8Z',
      category: 'naming',
      rating: null,
      likes: 0,
      dislikes: 0,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-11-28T11:17:55.507Z',
      updatedAt: '2018-11-28T11:17:55.557Z',
      author: {
        id: 6,
        fullName: 'Akanmu Christopher',
        avatarUrl: 'https://www.hahafakeurl.com/',
        roleId: 3,
        email: 'solomon.sulaiman@andela.com',
        bio: 'I am a girl that does magic tricks',
        followers: 0,
        following: 0
      }
    },
    {
      id: 17,
      title: 'Conditional JavaScript for Experts',
      slug: 'how-to-write-you-name-230111fe',
      description: 'If you want to learn a better and more memorable way',
      body: "let's talk about names, what is your name and what does it mean? How many people have laughed at your name and how many have cared about how you name was given to you?",
      readTime: 2400,
      articleImage: 'https://bit.ly/2B0QJjV',
      category: 'naming',
      rating: null,
      likes: 0,
      dislikes: 0,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-11-28T11:17:55.507Z',
      updatedAt: '2018-11-28T11:17:55.557Z',
      author: {
        id: 6,
        fullName: 'Maranatha Ilesanmi',
        avatarUrl: 'https://www.hahafakeurl.com/',
        roleId: 3,
        email: 'solomon.sulaiman@andela.com',
        bio: 'I am a girl that does magic tricks',
        followers: 0,
        following: 0
      }
    },
    {
      id: 16,
      title: 'Read This Before You Buy an iPhone XS',
      slug: 'how-to-write-you-name-230111fe',
      description: 'If you want to learn a better and more memorable way',
      body: "let's talk about names, what is your name and what does it mean? How many people have laughed at your name and how many have cared about how you name was given to you?",
      readTime: 2400,
      articleImage: 'https://bit.ly/2BXSBM3',
      category: 'naming',
      rating: null,
      likes: 0,
      dislikes: 0,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-11-28T11:17:55.507Z',
      updatedAt: '2018-11-28T11:17:55.557Z',
      author: {
        id: 6,
        fullName: 'Jalil Ogunniyi',
        avatarUrl: 'https://www.hahafakeurl.com/',
        roleId: 3,
        email: 'solomon.sulaiman@andela.com',
        bio: 'I am a girl that does magic tricks',
        followers: 0,
        following: 0
      }
    },
    {
      id: 15,
      title: 'How Do You Like Your Coffee',
      slug: 'how-to-write-you-name-230111fe',
      description: 'If you want to learn a better and more memorable way',
      body: "let's talk about names, what is your name and what does it mean? How many people have laughed at your name and how many have cared about how you name was given to you?",
      readTime: 2400,
      articleImage: 'https://bit.ly/2B4NZ51',
      category: 'naming',
      rating: null,
      likes: 0,
      dislikes: 0,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-11-28T11:17:55.507Z',
      updatedAt: '2018-11-28T11:17:55.557Z',
      author: {
        id: 6,
        fullName: 'Augustine Ezinwa',
        avatarUrl: 'https://www.hahafakeurl.com/',
        roleId: 3,
        email: 'solomon.sulaiman@andela.com',
        bio: 'I am a girl that does magic tricks',
        followers: 0,
        following: 0
      }
    },
    {
      id: 14,
      title: 'Andela Launches New Developer Programme',
      slug: 'how-to-write-you-name-230111fe',
      description: 'If you want to learn a better and more memorable way',
      body: "let's talk about names, what is your name and what does it mean? How many people have laughed at your name and how many have cared about how you name was given to you?",
      readTime: 2400,
      articleImage: 'https://bit.ly/2RHseiD',
      category: 'naming',
      rating: null,
      likes: 0,
      dislikes: 0,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-11-28T11:17:55.507Z',
      updatedAt: '2018-11-28T11:17:55.557Z',
      author: {
        id: 6,
        fullName: 'Abiodun Abudu',
        avatarUrl: 'https://www.hahafakeurl.com/',
        roleId: 3,
        email: 'solomon.sulaiman@andela.com',
        bio: 'I am a girl that does magic tricks',
        followers: 0,
        following: 0
      }
    },
    {
      id: 13,
      title: 'Andela Launches New Developer Programme',
      slug: 'how-to-write-you-name-230111fe',
      description: 'If you want to learn a better and more memorable way',
      body: "let's talk about names, what is your name and what does it mean? How many people have laughed at your name and how many have cared about how you name was given to you?",
      readTime: 2400,
      articleImage: 'https://bit.ly/2QaQE7D',
      category: 'naming',
      rating: null,
      likes: 0,
      dislikes: 0,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-11-28T11:17:55.507Z',
      updatedAt: '2018-11-28T11:17:55.557Z',
      author: {
        id: 6,
        fullName: 'Abiodun Abudu',
        avatarUrl: 'https://www.hahafakeurl.com/',
        roleId: 3,
        email: 'solomon.sulaiman@andela.com',
        bio: 'I am a girl that does magic tricks',
        followers: 0,
        following: 0
      }
    },
    {
      id: 12,
      title: 'Andela Launches New Developer Programme',
      slug: 'how-to-write-you-name-230111fe',
      description: 'If you want to learn a better and more memorable way',
      body: "let's talk about names, what is your name and what does it mean? How many people have laughed at your name and how many have cared about how you name was given to you?",
      readTime: 2400,
      articleImage: 'https://bit.ly/2QaQE7D',
      category: 'naming',
      rating: null,
      likes: 0,
      dislikes: 0,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-11-28T11:17:55.507Z',
      updatedAt: '2018-11-28T11:17:55.557Z',
      author: {
        id: 6,
        fullName: 'Abiodun Abudu',
        avatarUrl: 'https://www.hahafakeurl.com/',
        roleId: 3,
        email: 'solomon.sulaiman@andela.com',
        bio: 'I am a girl that does magic tricks',
        followers: 0,
        following: 0
      }
    },
    {
      id: 11,
      title: 'Andela Launches New Developer Programme',
      slug: 'how-to-write-you-name-230111fe',
      description: 'If you want to learn a better and more memorable way',
      body: "let's talk about names, what is your name and what does it mean? How many people have laughed at your name and how many have cared about how you name was given to you?",
      readTime: 2400,
      articleImage: 'https://bit.ly/2QaQE7D',
      category: 'naming',
      rating: null,
      likes: 0,
      dislikes: 0,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-11-28T11:17:55.507Z',
      updatedAt: '2018-11-28T11:17:55.557Z',
      author: {
        id: 6,
        fullName: 'Abiodun Abudu',
        avatarUrl: 'https://www.hahafakeurl.com/',
        roleId: 3,
        email: 'solomon.sulaiman@andela.com',
        bio: 'I am a girl that does magic tricks',
        followers: 0,
        following: 0
      }
    },
    {
      id: 10,
      title: 'Andela Launches New Developer Programme',
      slug: 'how-to-write-you-name-230111fe',
      description: 'If you want to learn a better and more memorable way',
      body: "let's talk about names, what is your name and what does it mean? How many people have laughed at your name and how many have cared about how you name was given to you?",
      readTime: 2400,
      articleImage: 'https://bit.ly/2QaQE7D',
      category: 'naming',
      rating: null,
      likes: 0,
      dislikes: 0,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-11-28T11:17:55.507Z',
      updatedAt: '2018-11-28T11:17:55.557Z',
      author: {
        id: 6,
        fullName: 'Abiodun Abudu',
        avatarUrl: 'https://www.hahafakeurl.com/',
        roleId: 3,
        email: 'solomon.sulaiman@andela.com',
        bio: 'I am a girl that does magic tricks',
        followers: 0,
        following: 0
      }
    },
    {
      id: 9,
      title: 'Andela Launches New Developer Programme',
      slug: 'how-to-write-you-name-230111fe',
      description: 'If you want to learn a better and more memorable way',
      body: "let's talk about names, what is your name and what does it mean? How many people have laughed at your name and how many have cared about how you name was given to you?",
      readTime: 2400,
      articleImage: 'https://bit.ly/2QaQE7D',
      category: 'naming',
      rating: null,
      likes: 0,
      dislikes: 0,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-11-28T11:17:55.507Z',
      updatedAt: '2018-11-28T11:17:55.557Z',
      author: {
        id: 6,
        fullName: 'Abiodun Abudu',
        avatarUrl: 'https://www.hahafakeurl.com/',
        roleId: 3,
        email: 'solomon.sulaiman@andela.com',
        bio: 'I am a girl that does magic tricks',
        followers: 0,
        following: 0
      }
    }
  ]
};
