export default {
  status: 'success',
  totalPages: 1,
  currentPage: 1,
  totalArticles: 18,
  articlesOnPage: 18,
  articles: [
    {
      id: 18,
      articleImage: 'https://bit.ly/2CaG1ce',
      title: 'Valinor',
      slug: 'team-valinore',
      description: 'Team valinor is a simulation team',
      body: 'They are handling authors haven product. Good luck, guys.',
      readTime: 3600,
      category: 'sports',
      rating: null,
      likes: 0,
      dislikes: 0,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-12-24T18:11:27.171Z',
      updatedAt: '2018-12-24T18:11:27.171Z',
      author: {
        id: 2,
        fullName: 'John Mike',
        avatarUrl: 'https://bit.ly/2UT01ax',
        roleId: 3,
        email: 'johnmike@andela.com',
        bio: null,
        followers: 0,
        following: 0
      }
    },
    {
      id: 17,
      articleImage: 'https://bit.ly/2CaG1ce',
      title: 'Jambolani',
      slug: 'south-africa-201e',
      description: 'Jambolani is the fifa ball',
      body: 'Jambolani is the fifa ball used in south africa 2010 world cup',
      readTime: 3600,
      category: 'sports',
      rating: null,
      likes: 0,
      dislikes: 0,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-12-24T18:11:27.171Z',
      updatedAt: '2018-12-24T18:11:27.171Z',
      author: {
        id: 2,
        fullName: 'John Mike',
        avatarUrl: 'https://bit.ly/2UT01ax',
        roleId: 3,
        email: 'johnmike@andela.com',
        bio: null,
        followers: 0,
        following: 0
      }
    },
    {
      id: 16,
      articleImage: 'https://bit.ly/2CaG1ce',
      title: 'My story at the beach',
      slug: 'My-story-at-the-beach-2324232323e',
      description: 'This is my story at the beach',
      body: 'Once upon a time in Mexico.. there was ...',
      readTime: 3600,
      category: 'sports',
      rating: null,
      likes: 0,
      dislikes: 0,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-12-24T18:11:27.171Z',
      updatedAt: '2018-12-24T18:11:27.171Z',
      author: {
        id: 1,
        fullName: 'John Doe',
        avatarUrl: 'https://bit.ly/2UT01ax',
        roleId: 3,
        email: 'johndoe@andela.com',
        bio: null,
        followers: 0,
        following: 0
      }
    },
    {
      id: 15,
      articleImage: 'https://bit.ly/2CaG1ce',
      title: 'Valinor',
      slug: 'team-valinord',
      description: 'Team valinor is a simulation team',
      body: 'They are handling authors haven product. Good luck, guys.',
      readTime: 3600,
      category: 'fashion',
      rating: null,
      likes: 0,
      dislikes: 0,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-12-24T18:11:27.171Z',
      updatedAt: '2018-12-24T18:11:27.171Z',
      author: {
        id: 2,
        fullName: 'John Mike',
        avatarUrl: 'https://bit.ly/2UT01ax',
        roleId: 3,
        email: 'johnmike@andela.com',
        bio: null,
        followers: 0,
        following: 0
      }
    },
    {
      id: 14,
      articleImage: 'https://bit.ly/2CaG1ce',
      title: 'Jambolani',
      slug: 'south-africa-201d',
      description: 'Jambolani is the fifa ball',
      body: 'Jambolani is the fifa ball used in south africa 2010 world cup',
      readTime: 3600,
      category: 'technology',
      rating: null,
      likes: 0,
      dislikes: 0,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-12-24T18:11:27.171Z',
      updatedAt: '2018-12-24T18:11:27.171Z',
      author: {
        id: 2,
        fullName: 'John Mike',
        avatarUrl: 'https://bit.ly/2UT01ax',
        roleId: 3,
        email: 'johnmike@andela.com',
        bio: null,
        followers: 0,
        following: 0
      }
    },
    {
      id: 13,
      articleImage: 'https://bit.ly/2CaG1ce',
      title: 'My story at the beach',
      slug: 'My-story-at-the-beach-2324232323d',
      description: 'This is my story at the beach',
      body: 'Once upon a time in Mexico.. there was ...',
      readTime: 3600,
      category: 'technology',
      rating: null,
      likes: 0,
      dislikes: 0,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-12-24T18:11:27.171Z',
      updatedAt: '2018-12-24T18:11:27.171Z',
      author: {
        id: 1,
        fullName: 'John Doe',
        avatarUrl: 'https://bit.ly/2UT01ax',
        roleId: 3,
        email: 'johndoe@andela.com',
        bio: null,
        followers: 0,
        following: 0
      }
    },
    {
      id: 12,
      articleImage: 'https://bit.ly/2CaG1ce',
      title: 'Valinor',
      slug: 'team-valinorc',
      description: 'Team valinor is a simulation team',
      body: 'They are handling authors haven product. Good luck, guys.',
      readTime: 3600,
      category: 'sports',
      rating: null,
      likes: 0,
      dislikes: 3,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-12-24T18:11:27.171Z',
      updatedAt: '2018-12-24T18:11:27.171Z',
      author: {
        id: 2,
        fullName: 'John Mike',
        avatarUrl: 'https://bit.ly/2UT01ax',
        roleId: 3,
        email: 'johnmike@andela.com',
        bio: null,
        followers: 0,
        following: 0
      }
    },
    {
      id: 11,
      articleImage: 'https://bit.ly/2CaG1ce',
      title: 'Jambolani',
      slug: 'south-africa-201c',
      description: 'Jambolani is the fifa ball',
      body: 'Jambolani is the fifa ball used in south africa 2010 world cup',
      readTime: 3600,
      category: 'fashion',
      rating: null,
      likes: 0,
      dislikes: 0,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-12-24T18:11:27.171Z',
      updatedAt: '2018-12-24T18:11:27.171Z',
      author: {
        id: 2,
        fullName: 'John Mike',
        avatarUrl: 'https://bit.ly/2UT01ax',
        roleId: 3,
        email: 'johnmike@andela.com',
        bio: null,
        followers: 0,
        following: 0
      }
    },
    {
      id: 10,
      articleImage: 'https://bit.ly/2CaG1ce',
      title: 'My story at the beach',
      slug: 'My-story-at-the-beach-2324232323c',
      description: 'This is my story at the beach',
      body: 'Once upon a time in Mexico.. there was ...',
      readTime: 3600,
      category: 'sports',
      rating: null,
      likes: 0,
      dislikes: 0,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-12-24T18:11:27.171Z',
      updatedAt: '2018-12-24T18:11:27.171Z',
      author: {
        id: 1,
        fullName: 'John Doe',
        avatarUrl: 'https://bit.ly/2UT01ax',
        roleId: 3,
        email: 'johndoe@andela.com',
        bio: null,
        followers: 0,
        following: 0
      }
    },
    {
      id: 9,
      articleImage: 'https://bit.ly/2CaG1ce',
      title: 'Valinor',
      slug: 'team-valinorb',
      description: 'Team valinor is a simulation team',
      body: 'They are handling authors haven product. Good luck, guys.',
      readTime: 3600,
      category: 'sports',
      rating: null,
      likes: 0,
      dislikes: 1,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-12-24T18:11:27.171Z',
      updatedAt: '2018-12-24T18:11:27.171Z',
      author: {
        id: 2,
        fullName: 'John Mike',
        avatarUrl: 'https://bit.ly/2UT01ax',
        roleId: 3,
        email: 'johnmike@andela.com',
        bio: null,
        followers: 0,
        following: 0
      }
    },
    {
      id: 8,
      articleImage: 'https://bit.ly/2CaG1ce',
      title: 'Jambolani',
      slug: 'south-africa-201b',
      description: 'Jambolani is the fifa ball',
      body: 'Jambolani is the fifa ball used in south africa 2010 world cup',
      readTime: 3600,
      category: 'technology',
      rating: null,
      likes: 0,
      dislikes: 0,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-12-24T18:11:27.171Z',
      updatedAt: '2018-12-24T18:11:27.171Z',
      author: {
        id: 2,
        fullName: 'John Mike',
        avatarUrl: 'https://bit.ly/2UT01ax',
        roleId: 3,
        email: 'johnmike@andela.com',
        bio: null,
        followers: 0,
        following: 0
      }
    },
    {
      id: 7,
      articleImage: 'https://bit.ly/2CaG1ce',
      title: 'My story at the beach',
      slug: 'My-story-at-the-beach-2324232323b',
      description: 'This is my story at the beach',
      body: 'Once upon a time in Mexico.. there was ...',
      readTime: 3600,
      category: 'fashion',
      rating: null,
      likes: 0,
      dislikes: 0,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-12-24T18:11:27.171Z',
      updatedAt: '2018-12-24T18:11:27.171Z',
      author: {
        id: 1,
        fullName: 'John Doe',
        avatarUrl: 'https://bit.ly/2UT01ax',
        roleId: 3,
        email: 'johndoe@andela.com',
        bio: null,
        followers: 0,
        following: 0
      }
    },
    {
      id: 6,
      articleImage: 'https://bit.ly/2CaG1ce',
      title: 'Valinor',
      slug: 'team-valinora',
      description: 'Team valinor is a simulation team',
      body: 'They are handling authors haven product. Good luck, guys.',
      readTime: 3600,
      category: 'technology',
      rating: null,
      likes: 0,
      dislikes: 0,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-12-24T18:11:27.171Z',
      updatedAt: '2018-12-24T18:11:27.171Z',
      author: {
        id: 2,
        fullName: 'John Mike',
        avatarUrl: 'https://bit.ly/2UT01ax',
        roleId: 3,
        email: 'johnmike@andela.com',
        bio: null,
        followers: 0,
        following: 0
      }
    },
    {
      id: 5,
      articleImage: 'https://bit.ly/2CaG1ce',
      title: 'Jambolani',
      slug: 'south-africa-201a',
      description: 'Jambolani is the fifa ball',
      body: 'Jambolani is the fifa ball used in south africa 2010 world cup',
      readTime: 3600,
      category: 'fashion',
      rating: null,
      likes: 1,
      dislikes: 1,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-12-24T18:11:27.171Z',
      updatedAt: '2018-12-24T18:11:27.171Z',
      author: {
        id: 2,
        fullName: 'John Mike',
        avatarUrl: 'https://bit.ly/2UT01ax',
        roleId: 3,
        email: 'johnmike@andela.com',
        bio: null,
        followers: 0,
        following: 0
      }
    },
    {
      id: 4,
      articleImage: 'https://bit.ly/2CaG1ce',
      title: 'My story at the beach',
      slug: 'My-story-at-the-beach-2324232323a',
      description: 'This is my story at the beach',
      body: 'Once upon a time in Mexico.. there was ...',
      readTime: 3600,
      category: 'technology',
      rating: null,
      likes: 1,
      dislikes: 0,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-12-24T18:11:27.171Z',
      updatedAt: '2018-12-24T18:11:27.171Z',
      author: {
        id: 1,
        fullName: 'John Doe',
        avatarUrl: 'https://bit.ly/2UT01ax',
        roleId: 3,
        email: 'johndoe@andela.com',
        bio: null,
        followers: 0,
        following: 0
      }
    },
    {
      id: 3,
      articleImage: 'https://bit.ly/2CaG1ce',
      title: 'Valinor',
      slug: 'team-valinor',
      description: 'Team valinor is a simulation team',
      body: 'They are handling authors haven product. Good luck, guys.',
      readTime: 3600,
      category: 'fashion',
      rating: null,
      likes: 1,
      dislikes: 0,
      status: 'publish',
      commentsCount: 0,
      createdAt: '2018-12-24T18:11:27.171Z',
      updatedAt: '2018-12-24T18:11:27.171Z',
      author: {
        id: 2,
        fullName: 'John Mike',
        avatarUrl: 'https://bit.ly/2UT01ax',
        roleId: 3,
        email: 'johnmike@andela.com',
        bio: null,
        followers: 0,
        following: 0
      }
    },
    {
      id: 2,
      articleImage: 'https://bit.ly/2CaG1ce',
      title: 'Jambolani',
      slug: 'south-africa-201',
      description: 'Jambolani is the fifa ball',
      body: 'Jambolani is the fifa ball used in south africa 2010 world cup',
      readTime: 3600,
      category: 'technology',
      rating: null,
      likes: 3,
      dislikes: 0,
      status: 'publish',
      commentsCount: 4,
      createdAt: '2018-12-24T18:11:27.171Z',
      updatedAt: '2018-12-24T18:11:27.171Z',
      author: {
        id: 2,
        fullName: 'John Mike',
        avatarUrl: 'https://bit.ly/2UT01ax',
        roleId: 3,
        email: 'johnmike@andela.com',
        bio: null,
        followers: 0,
        following: 0
      }
    },
    {
      id: 1,
      articleImage: 'https://bit.ly/2CaG1ce',
      title: 'My story at the beach',
      slug: 'My-story-at-the-beach-2324232323',
      description: 'This is my story at the beach',
      body: 'Once upon a time in Mexico.. there was ...',
      readTime: 3600,
      category: 'sports',
      rating: null,
      likes: 2,
      dislikes: 0,
      status: 'publish',
      commentsCount: 6,
      createdAt: '2018-12-24T18:11:27.171Z',
      updatedAt: '2018-12-24T18:11:27.171Z',
      author: {
        id: 1,
        fullName: 'John Doe',
        avatarUrl: 'https://bit.ly/2UT01ax',
        roleId: 3,
        email: 'johndoe@andela.com',
        bio: null,
        followers: 0,
        following: 0
      }
    }
  ]
};
